#!/bin/bash

echo -n "$GC_SA" | base64 -d > bot/creds.json

cat << EOF > bot/.env
TOKEN=$TOKEN
SERVER_ID=$SERVER_ID
MAIN_CHANNEL_ID=$MAIN_CHANNEL_ID
LEADERBOARD_CHANNEL_ID=$LEADERBOARD_CHANNEL_ID
ADMIN_ROLE_ID=$ADMIN_ROLE_ID
EOF